name: Build and Push to ECR

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push database image
        uses: docker/build-push-action@v5
        with:
          context: database
          file: database/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/keda-postgres:database-${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/keda-postgres:database-buildcache
          cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/keda-postgres:database-buildcache,mode=max

      - name: Build and push job-consumer image
        uses: docker/build-push-action@v5
        with:
          context: job-consumer
          file: job-consumer/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/keda-postgres:job-consumer-${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/keda-postgres:job-consumer-buildcache
          cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/keda-postgres:job-consumer-buildcache,mode=max

      - name: Build and push job-pusher image
        uses: docker/build-push-action@v5
        with:
          context: job-pusher
          file: job-pusher/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/keda-postgres:job-pusher-${{ github.sha }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/keda-postgres:job-pusher-buildcache
          cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/keda-postgres:job-pusher-buildcache,mode=max
