name: Build and Push to ECR

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build database image
        run: |
          docker build -f database/Dockerfile -t keda-postgres:database-${{ github.sha }} database
      - name: Tag database image
        run: |
          docker tag keda-postgres:database-${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/keda-postgres:database-${{ github.sha }}

      - name: Push database image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/keda-postgres:database-${{ github.sha }}
      - name: Build job-consumer image
        run: |
          docker build -f job-consumer/Dockerfile -t keda-postgres:job-consumer-${{ github.sha }} job-consumer
      - name: Tag job-consumer image
        run: |
          docker tag keda-postgres:job-consumer-${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/keda-postgres:job-consumer-${{ github.sha }}

      - name: Push job-consumer image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/keda-postgres:job-consumer-${{ github.sha }}
      - name: Build job-consumer image
        run: |
          docker build -f job-pusher/Dockerfile -t keda-postgres:job-pusher-${{ github.sha }} job-pusher
      - name: Tag job-pusher image
        run: |
          docker tag keda-postgres:job-pusher-${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/keda-postgres:job-pusher-${{ github.sha }}

      - name: Push job-pusher image
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/keda-postgres:job-pusher-${{ github.sha }}